//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRPA.MiWSPortafirmas_DESA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tipoFirma", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    public enum tipoFirma : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cascada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paralela = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="document", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    [System.SerializableAttribute()]
    public partial class document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b64 {
            get {
                return this.b64Field;
            }
            set {
                if ((object.ReferenceEquals(this.b64Field, value) != true)) {
                    this.b64Field = value;
                    this.RaisePropertyChanged("b64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                if ((object.ReferenceEquals(this.identifierField, value) != true)) {
                    this.identifierField = value;
                    this.RaisePropertyChanged("identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mime {
            get {
                return this.mimeField;
            }
            set {
                if ((object.ReferenceEquals(this.mimeField, value) != true)) {
                    this.mimeField = value;
                    this.RaisePropertyChanged("mime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sign {
            get {
                return this.signField;
            }
            set {
                if ((object.ReferenceEquals(this.signField, value) != true)) {
                    this.signField = value;
                    this.RaisePropertyChanged("sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portafirmas_Modify_DTO", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    [System.SerializableAttribute()]
    public partial class Portafirmas_Modify_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string createdRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdRequestId {
            get {
                return this.createdRequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.createdRequestIdField, value) != true)) {
                    this.createdRequestIdField = value;
                    this.RaisePropertyChanged("createdRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
    [System.SerializableAttribute()]
    public partial class ErroresEadmon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portafirmas_Query_DTO", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    [System.SerializableAttribute()]
    public partial class Portafirmas_Query_DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APIRPA.MiWSPortafirmas_DESA.documentList[] documentListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APIRPA.MiWSPortafirmas_DESA.signer[] signersListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APIRPA.MiWSPortafirmas_DESA.documentList[] documentList {
            get {
                return this.documentListField;
            }
            set {
                if ((object.ReferenceEquals(this.documentListField, value) != true)) {
                    this.documentListField = value;
                    this.RaisePropertyChanged("documentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.requestStatusField, value) != true)) {
                    this.requestStatusField = value;
                    this.RaisePropertyChanged("requestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APIRPA.MiWSPortafirmas_DESA.signer[] signersList {
            get {
                return this.signersListField;
            }
            set {
                if ((object.ReferenceEquals(this.signersListField, value) != true)) {
                    this.signersListField = value;
                    this.RaisePropertyChanged("signersList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="documentList", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    [System.SerializableAttribute()]
    public partial class documentList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APIRPA.MiWSPortafirmas_DESA.document documentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APIRPA.MiWSPortafirmas_DESA.document document {
            get {
                return this.documentField;
            }
            set {
                if ((object.ReferenceEquals(this.documentField, value) != true)) {
                    this.documentField = value;
                    this.RaisePropertyChanged("document");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="signer", Namespace="http://schemas.datacontract.org/2004/07/eadmon.DTO")]
    [System.SerializableAttribute()]
    public partial class signer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signStateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surname1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surname2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signState {
            get {
                return this.signStateField;
            }
            set {
                if ((object.ReferenceEquals(this.signStateField, value) != true)) {
                    this.signStateField = value;
                    this.RaisePropertyChanged("signState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signStateDate {
            get {
                return this.signStateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.signStateDateField, value) != true)) {
                    this.signStateDateField = value;
                    this.RaisePropertyChanged("signStateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname1 {
            get {
                return this.surname1Field;
            }
            set {
                if ((object.ReferenceEquals(this.surname1Field, value) != true)) {
                    this.surname1Field = value;
                    this.RaisePropertyChanged("surname1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname2 {
            get {
                return this.surname2Field;
            }
            set {
                if ((object.ReferenceEquals(this.surname2Field, value) != true)) {
                    this.surname2Field = value;
                    this.RaisePropertyChanged("surname2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiWSPortafirmas_DESA.IPortafirmas_SEC_")]
    public interface IPortafirmas_SEC_ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/createRequest", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/createRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APIRPA.MiWSPortafirmas_DESA.ErroresEadmon), Action="http://tempuri.org/IPortafirmas_SEC_/createRequestErroresEadmonFault", Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
        APIRPA.MiWSPortafirmas_DESA.Portafirmas_Modify_DTO createRequest(string subject, string text, string reference, APIRPA.MiWSPortafirmas_DESA.tipoFirma tipoFirma, string[] signers, APIRPA.MiWSPortafirmas_DESA.document[] documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/createRequest", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/createRequestResponse")]
        System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Modify_DTO> createRequestAsync(string subject, string text, string reference, APIRPA.MiWSPortafirmas_DESA.tipoFirma tipoFirma, string[] signers, APIRPA.MiWSPortafirmas_DESA.document[] documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/requestState", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/requestStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APIRPA.MiWSPortafirmas_DESA.ErroresEadmon), Action="http://tempuri.org/IPortafirmas_SEC_/requestStateErroresEadmonFault", Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
        APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO requestState(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/requestState", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/requestStateResponse")]
        System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO> requestStateAsync(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/docList", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/docListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APIRPA.MiWSPortafirmas_DESA.ErroresEadmon), Action="http://tempuri.org/IPortafirmas_SEC_/docListErroresEadmonFault", Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
        APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO docList(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/docList", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/docListResponse")]
        System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO> docListAsync(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/downloadDocument", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/downloadDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APIRPA.MiWSPortafirmas_DESA.ErroresEadmon), Action="http://tempuri.org/IPortafirmas_SEC_/downloadDocumentErroresEadmonFault", Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
        APIRPA.MiWSPortafirmas_DESA.document downloadDocument(string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/downloadDocument", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/downloadDocumentResponse")]
        System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.document> downloadDocumentAsync(string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/downloadSignDocument", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/downloadSignDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APIRPA.MiWSPortafirmas_DESA.ErroresEadmon), Action="http://tempuri.org/IPortafirmas_SEC_/downloadSignDocumentErroresEadmonFault", Name="ErroresEadmon", Namespace="http://schemas.datacontract.org/2004/07/eadmon")]
        APIRPA.MiWSPortafirmas_DESA.document downloadSignDocument(string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPortafirmas_SEC_/downloadSignDocument", ReplyAction="http://tempuri.org/IPortafirmas_SEC_/downloadSignDocumentResponse")]
        System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.document> downloadSignDocumentAsync(string documentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPortafirmas_SEC_Channel : APIRPA.MiWSPortafirmas_DESA.IPortafirmas_SEC_, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Portafirmas_SEC_Client : System.ServiceModel.ClientBase<APIRPA.MiWSPortafirmas_DESA.IPortafirmas_SEC_>, APIRPA.MiWSPortafirmas_DESA.IPortafirmas_SEC_ {
        
        public Portafirmas_SEC_Client() {
        }
        
        public Portafirmas_SEC_Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Portafirmas_SEC_Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Portafirmas_SEC_Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Portafirmas_SEC_Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public APIRPA.MiWSPortafirmas_DESA.Portafirmas_Modify_DTO createRequest(string subject, string text, string reference, APIRPA.MiWSPortafirmas_DESA.tipoFirma tipoFirma, string[] signers, APIRPA.MiWSPortafirmas_DESA.document[] documents) {
            return base.Channel.createRequest(subject, text, reference, tipoFirma, signers, documents);
        }
        
        public System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Modify_DTO> createRequestAsync(string subject, string text, string reference, APIRPA.MiWSPortafirmas_DESA.tipoFirma tipoFirma, string[] signers, APIRPA.MiWSPortafirmas_DESA.document[] documents) {
            return base.Channel.createRequestAsync(subject, text, reference, tipoFirma, signers, documents);
        }
        
        public APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO requestState(string requestId) {
            return base.Channel.requestState(requestId);
        }
        
        public System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO> requestStateAsync(string requestId) {
            return base.Channel.requestStateAsync(requestId);
        }
        
        public APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO docList(string requestId) {
            return base.Channel.docList(requestId);
        }
        
        public System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.Portafirmas_Query_DTO> docListAsync(string requestId) {
            return base.Channel.docListAsync(requestId);
        }
        
        public APIRPA.MiWSPortafirmas_DESA.document downloadDocument(string documentId) {
            return base.Channel.downloadDocument(documentId);
        }
        
        public System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.document> downloadDocumentAsync(string documentId) {
            return base.Channel.downloadDocumentAsync(documentId);
        }
        
        public APIRPA.MiWSPortafirmas_DESA.document downloadSignDocument(string documentId) {
            return base.Channel.downloadSignDocument(documentId);
        }
        
        public System.Threading.Tasks.Task<APIRPA.MiWSPortafirmas_DESA.document> downloadSignDocumentAsync(string documentId) {
            return base.Channel.downloadSignDocumentAsync(documentId);
        }
    }
}
